#!/usr/bin/env bash
# Bash script that transfers a file from client to server

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit;
else
	scp -i "$1" -o StrictHostKeyChecking=no "$2" "$3"@"$4": ~/
fi;	
