#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
apt-get update
apt-get -y install nginx
sed -i "15i\add_header X-Served-By $hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
