#!/usr/bin/env bash
#configure nginx to listen to port 80
if ! sudo service nginx status >/dev/null 2>&1; then 
	sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/nginx.config
	service nginx restart
fi
