#!/usr/bin/env bash
# Loops 1 to 10 to display "Best School" 
#"bad luck" on 4th loop and "good luck" on 8th loop iterations.

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
		(( i++ ))
done
