#!/usr/bin/env bash
# Display 1 to 20 "bad luck from China" on 4th iteration
# "bad luck from Japan" on 9th iteration
# "bad luck from Italy" on 17th iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japana";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
